### PR TITLE
ааааааааа

### PR DESCRIPTION
**Pull request by ghost**
я кароч просто попробовать эту штуку

### CODE REVIEW

**Comment by s0me1newithhand7s** [comment]
good fork, but i wont use as it is against philosophy :D

**Comment by ghost** [comment]
@aski425, did you know you violated copyright? a repository without a license is considered proprietary

**Comment by s0me1newithhand7s** [comment]
> @aski425, did you know you violated copyright? a repository without a license is considered proprietary

not the main problem here; this repo is reference doc and idea behind this config isn't meeted here - Askhat's config his personal config.

**Comment by ghost** [comment]
> > @aski425, did you know you violated copyright? a repository without a license is considered proprietary
> 
> not the main problem here; this repo is reference doc and idea behind this config isn't meeted here - Askhat's config his personal config.

ok

**Pull request closed without merging**
